---
title: LidDrivenCavity

#  number of iterations
iterations: 10

# Square/cubic mesh generation parameters
# cells per side
cps: 16
# domain size
L: 1.0

relaxation_factor:
  u: 0.9
  v: 0.9
  w: 0.9
  p: 0.1

target_residual: 1.0e-10

### VALUES BELOW THIS POINT ARE NOT CURRENTLY USED

#reference_numbers:
#    pressure: 101325.0
#    temperature: 289.0
#    density: 1.0
#    viscosity: 1.0e-03
#    pref_at_cell: 4096

#solve:
#  w: off

#init: 
#  type: user

#monitor_cell: 1990

# 1 = central
#convection_scheme:
#  u: 1 
#  v: 1
#  w: 1

#blending_factor:
#  u: 1.0
#  v: 1.0
#  w: 1.0
  
#output:
#  every: 1000

#post:
#  type: center
#  variables: [u, v, w, p]

variables:
  store_residuals: false
  n_variables: 5
  variable_1:
    name: u
    type: central
  variable_2:
    name: v
    type: upwind
  variable_3:
    name: w
    type: upwind
  variable_4:
    name: p
    type: central
  variable_5:
    name: p_prime
    type: central

boundaries:
  n_boundaries: 6
  boundary_1: 
    name: left
    type: dirichlet
    value: 0
    variable_p:
      type: extrapolate
    variable_p_prime:
      type: neumann
      value: 0
  boundary_2:
    name: right
    type: dirichlet
    value: 0
    variable_p:
      type: extrapolate
    variable_p_prime:
      type: neumann
      value: 0
  boundary_3:
    name: bottom
    type: dirichlet
    value: 0
    variable_p:
      type: extrapolate
    variable_p_prime:
      type: neumann
      value: 0
  boundary_4:
    name: top
    type: dirichlet
    value: 0
    variable_u:
      type: dirichlet
      value: 1
    variable_p:
      type: extrapolate
    variable_p_prime:
      type: neumann
      value: 0
  boundary_5:
    name: back
    type: neumann
    value: 0
    variable_w:
      type: dirichlet
      value: 0
  boundary_6:
    name: front
    type: neumann
    value: 0
    variable_w:
      type: dirichlet
      value: 0
